title: blog.neils.tech
email: me@neils.tech
description: >-
  Notes on software development, by Neils Christoffersen.
baseurl: ""
url: "https://blog.neils.tech"
github_username:  neilsc

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
